#!/usr/bin/env bash

set -euo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ -z ${1+x} ]; then
    echo "Usage: ./run PORT"
    exit 1
fi

nixos-rebuild -I nixos-config=$DIR/example.nix build-vm
QEMU_NET_OPTS="hostfwd=tcp::$1-:3000" ./result/bin/run-*-vm
